Repository Azure/jumpstart-apps, pull requests merged in 2024-10, with the labels that each got.

#20 Added docker file, brought in routing and added pages
  agora/main_ui/src/Dockerfile
  agora/main_ui/src/package-lock.json
  agora/main_ui/src/package.json
  agora/main_ui/src/src/App.tsx
  agora/main_ui/src/src/components/Cards.tsx
  agora/main_ui/src/src/pages/home/index.tsx
  agora/main_ui/src/src/pages/login/index.tsx
  agora/main_ui/src/src/pages/pagesData.tsx
  agora/main_ui/src/src/pages/router.tsx
  agora/main_ui/src/src/pages/storemanager/index.tsx
  agora/main_ui/src/src/types/router.types.ts
  agora/main_ui/src/yarn.lock
Labels: changes-required

#35 minor main.py fixes
  scenarios/acsa_fault_detection/main.py
Labels: bug

#38 Update hello_arc tag for 1.0.0 on MCR
  arcbox/hello_arc/yaml/hello_arc.yaml
Labels: enhancement, agora

#91 Cerebral - RAG at the Edge and rename to Cerebral
  .gitignore
  agora/cerebral_api/operations/genie-api.yaml
  agora/cerebral_api/operations/genie-chroma.yaml
  agora/cerebral_api/operations/genie-simulator.yaml
  agora/cerebral_api/operations/influxdb-setup.yaml
  agora/cerebral_api/operations/influxdb.yaml
  agora/cerebral_api/operations/mssql-setup.yaml
  agora/cerebral_api/operations/mssql.yaml
  agora/cerebral_api/operations/observability-prometheus.yaml
  agora/cerebral_api/operations/setup-sql.sh
  agora/cerebral_api/src/Dockerfile
  agora/cerebral_api/src/InfluxDBHandler.py
  agora/cerebral_api/src/SpeechToText.py
  agora/cerebral_api/src/SqlDBHandler.py
  agora/cerebral_api/src/app.py
  agora/cerebral_api/src/llm.py
  agora/cerebral_api/src/main.py
  agora/cerebral_api/src/prompts.json
  agora/cerebral_api/src/requirements.txt
  agora/cerebral_api/src/supervisor.conf
  agora/cerebral_rag/operations/chroma.yaml
  agora/cerebral_rag/src/app_slm.py
  agora/cerebral_rag/src/app_ws.py
  agora/cerebral_rag/src/dockerfile
  agora/cerebral_rag/src/docs/Automated Checkout System User Manual for Contoso Retail Hypermarket.pdf
  agora/cerebral_rag/src/docs/HVAC System User Manual for Contoso Hypermarket.pdf
  agora/cerebral_rag/src/docs/Refrigeration System User Manual for Contoso Retail Hypermarket.pdf
  agora/cerebral_rag/src/docs/Scale System User Manual for Contoso Retail Hypermarket.pdf
  agora/cerebral_rag/src/docs/SmartShelf System User Manual for Contoso Retail Hypermarket.pdf
  agora/cerebral_rag/src/indexer.py
  agora/cerebral_rag/src/readme.md
  agora/cerebral_rag/src/requirements.txt
  agora/cerebral_rag/src/templates/index.html
  agora/cerebral_rag/src/tools/phi3-qa.py
  agora/cerebral_rag/src/tools/test2.py
  agora/cerebral_rag/src/tools/test3.py
  agora/cerebral_rag/src/tools/testconnection.py
  agora/cerebral_simulator/src/Dockerfile
  agora/cerebral_simulator/src/app.py
  agora/cerebral_simulator/src/bak/products.json
  agora/cerebral_simulator/src/bak/store_simulator.py
  agora/cerebral_simulator/src/products.json
  agora/cerebral_simulator/src/requirements.txt
  agora/cerebral_simulator/src/store_simulator.py
  agora/cerebral_simulator/src/stores.json
Labels: agora, cerebral

#92 Added person-video extraction
  agora/shopper_insights_api/src/video_processor.py
Labels: agora
